### ISSUE TITLE
VUnit testbench generation fails

### ISSUE THREAD

**Issue by lukipedio** [TerosTechnology/vscode-terosHDL#10]
On a specific file (attached) the VUnit testbench generation fails.

![image](https://user-images.githubusercontent.com/16959881/88376639-19d2e580-cd9e-11ea-905d-06703e4d31e8.png)

**Comment by lukipedio** [comment]
[common.zip](https://github.com/TerosTechnology/vscode-terosHDL/files/4971113/common.zip)

**Comment by qarlosalberto** [comment]
Thank you @lukipedio !! 

Due to the holidays I'm not programming much in my free time. Let me a time to fix it ;)

**Comment by lukipedio** [comment]
Now, with v0.0.3, VUnit testbench generation works fine!
