### ISSUE TITLE
Format result not applied to current document.

### ISSUE THREAD

**Issue by suzizecat** [TerosTechnology/vscode-terosHDL#104]
Under unknown conditions, formatter output seems to not be pulled back from temporary file to current editor.
Seen using S3SV formatter, under RH7 on a compute farm. 
No particular message shown in the debug tools. 

Some checks should be added to notify the user if something went wrong in the process.

**Comment by qarlosalberto** [comment]
Also, It would be necessary a python3 path checker. It will be common to other features, as dependencies viewer.

**Comment by qarlosalberto** [comment]
@suzizecat is it fixed?

**Comment by suzizecat** [comment]
I have this issue on windows. Investigating what's going on.
As far as I can currently see, the temp file is created with file content but the formatter isn't ran on it.

What's weird is that I have a message in the debug tool which print the command used. If I copy-paste this command in a terminal, the temp file is formatted as intended.
