### ISSUE TITLE
Ergonomic suggestion for project UI

### ISSUE THREAD

**Issue by GlenNicholls** [TerosTechnology/vscode-terosHDL#115]
In the project UI, when I add a lot of files using a CSV, it opens with all of the library tabs expanded:
![image](https://user-images.githubusercontent.com/17171913/113931938-4efa5900-97b0-11eb-9e7a-753c74596596.png)

Instead, I think it should open with all of the library lists closed like so:
![image](https://user-images.githubusercontent.com/17171913/113932042-69343700-97b0-11eb-88d9-c0d83806dade.png)

**Comment by qarlosalberto** [comment]
I agree.
