### ISSUE TITLE
Modelsim Linter - vcom

### ISSUE THREAD

**Issue by skaester** [TerosTechnology/vscode-terosHDL#136]
For Modelsim as Linter, the wrong path settings are used:
![image](https://user-images.githubusercontent.com/54840663/116413709-2954f280-a838-11eb-921f-16bf033c53d3.png)

here the Result of the debugger:

![image](https://user-images.githubusercontent.com/54840663/116413879-4a1d4800-a838-11eb-96f9-9ffc22e253a7.png)

The "undefined" at the end of the path (Debugger output) must be replaced by "vcom".

**Comment by Nemmerle** [comment]
I have the same problem in a Windows 10 machine.

However, the problem is not shown in an OpenSuse Linux.

```bash
[colibri][info] Linting with command: vcom -quiet -nologo -2008 
```

**Comment by qarlosalberto** [comment]
We will fix it in the next version.
