### ISSUE TITLE
Where to install?

### ISSUE THREAD

**Issue by el3ctrician** [TerosTechnology/vscode-terosHDL#14]
Hello,

i am so sorry but i have a very basic question: is this plugin available on the vscode marketplace. I am not able to find it... should it be installed manually ?

Thanks

**Comment by smgl9** [comment]
Hello,

It has to be installed manually, for now it's a beta version so it's not published in the marketplace yet. 

You can download the VSIX file and install it manually.
https://github.com/TerosTechnology/vscode-terosHDL/releases

**Comment by el3ctrician** [comment]
thanks al lot
