### ISSUE TITLE
Go To Definition not working

### ISSUE THREAD

**Issue by walternestor** [TerosTechnology/vscode-terosHDL#140]
Hi,

I´m using TerosHDL in Windows 10 and the "Go To Definition" feature is not working. 

It always shows "Definition not found for '...'"

![image](https://user-images.githubusercontent.com/3493372/117584778-38179100-b0e5-11eb-9393-b8138174db6e.png)

Module Documentation and Dependency Viewer are working ok. 

Execution environment:
Windows 10
Visual Studio - 1.56.0
TerosHDL - 0.1.4
Python - 3.9.5 (tested also with python 3.7.7)

Kind Regards,
Walter Guse

**Comment by qarlosalberto** [comment]
Fixed in the next version.
