### ISSUE TITLE
always `Downloading language server...`

### ISSUE THREAD

**Issue by heartacker** [TerosTechnology/vscode-terosHDL#145]
using v0.1.91
![image](https://user-images.githubusercontent.com/1876302/118578753-4fc6d780-b7bf-11eb-932b-4bb79272e3b0.png)

**Comment by smgl9** [comment]
Hi!
v0.1.91 is a beta for now. It may have many bugs. Language server is an ongoing development :)

Thanks for the feedback

**Comment by smgl9** [comment]
@heartacker  It should be fixed in the last beta version. Just in case you would like to test it: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest
