### ISSUE TITLE
Remove a single file from project

### ISSUE THREAD

**Issue by smgl9** [TerosTechnology/vscode-terosHDL#150]
In master branch, trying to remove a single file in the project manager removes all files in the active project.

**Comment by suzizecat** [comment]
Are you sure ?
For me it seems to work correctly on master. However the removed file is not the one near which you clicked the "remove" button, but the one actually selected. So, if you select a library and hit "-" near a file, you'll actually remove the library.

**Comment by qarlosalberto** [comment]
You are right. There are 2 solutions:
- Remove "-"
- If you click "-" remove only the file, not all selected files/libraries.

**Comment by suzizecat** [comment]
If you can, in my opinion, the best way would be: 
 - If you have selected the item you are removing, then no problem, remove every selected items
 - Otherwise, only remove the item you have clicked "-" on.

**Comment by qarlosalberto** [comment]
It's a very good idea! I will do it

**Comment by qarlosalberto** [comment]
Fixed.
