### ISSUE TITLE
Dependency viewer fails to open

### ISSUE THREAD

**Issue by lukipedio** [TerosTechnology/vscode-terosHDL#155]
I am getting this error:

![image](https://user-images.githubusercontent.com/16959881/119618714-7dd19a80-be03-11eb-8a43-fc8be029c033.png)

while trying to open dependency viewer in TerosHDL 0.1.4.

My system path points to Python 3.9 installation.

I have tried also to add that path in the extension configuration, but no luck.

**Comment by lukipedio** [comment]
ok. I'll check it on next release!

**Comment by lukipedio** [comment]
I have installed the latest release beta (it appears to be v0.1.91).
It doesn't work yet. 
This is the message I get in the devtools: https://prnt.sc/13fulz4

**Comment by qarlosalberto** [comment]
It's related to: https://github.com/TerosTechnology/vscode-terosHDL/issues/156

Go to TerosHDL settings and set your python3 path.

**Comment by smgl9** [comment]
@lukipedio  In a windows shell type: `where python3` and copy the entire path in teroshdl python path settings, as @qarlosalberto  mentioned.
The path must be something like this: `C:\Users\isma\AppData\Local\Microsoft\WindowsApps\python3.exe`

**Comment by lukipedio** [comment]
Unfortunately, it doesn't work in my case.
I still get an error about SVG file.
![image](https://user-images.githubusercontent.com/16959881/119691254-b6489700-be4a-11eb-839a-81e3627330ad.png)
But if I save it in Markdown format or HTML, the figure is there in a good SVG output file.

**Comment by qarlosalberto** [comment]
@lukipedio where do you have the error, in the dependency viewer?

**Comment by lukipedio** [comment]
@qarlosalberto Yes, in the dependency viewer.

**Comment by qarlosalberto** [comment]
Have you installed VUnit?

**Comment by lukipedio** [comment]
My fault, sorry.
Too many Python installations.... 
I have installed vunit-hdl for the one which is returned by 'where python3' and now everything works just fine.

![image](https://user-images.githubusercontent.com/16959881/119857655-0b041480-bf14-11eb-9af4-8b97cf5fcb06.png)

**Comment by qarlosalberto** [comment]
Good!
