### ISSUE TITLE
SV documenter crash when module first port is an interface

### ISSUE THREAD

**Issue by suzizecat** [TerosTechnology/vscode-terosHDL#187]
**Describe the bug**
When starting the documenter preview (it must *not* be started beforehand) for a SystemVerilog module which first port is an interface, TerosHDL crashes altogether.

**To Reproduce**
1. Start a new instance of vscode (or reload the window)
2. On a file containing the given MWE, start the documentation preview.

It crashes.
If you move the interface on the second position, it will work as expected. You can then put it back on first position, save, and it will still work.

**Code**
```sv
module my_module (
    if_myinterface.slave sif_interface,
    output logic [3:0] o_something 
);
endmodule
```

**Please complete the following information:**
 - OS: All (Windows and RHEL7)
 - VSCode version latest and 1.48.1

**Additional context**
The developper tools seems to blame tree-sitter : 
```txt
c:\Users\jfaucher\.vscode\extensions\teros-technology.teroshdl-0.1.91\node_modules\jsteros\node_modules\web-tree-sitter\tree-sitter.js:1
[...]
[RuntimeError: abort(TypeError: Cannot read property 'replace' of undefined). Build with -s ASSERTIONS=1 for more info.
	at process.we (c:\Users\jfaucher\.vscode\extensions\teros-technology.teroshdl-0.1.91\node_modules\jsteros\node_modules\web-tree-sitter\tree-sitter.js:1:11401)
	at process.emit (events.js:327:22)
	at process.EventEmitter.emit (domain.js:467:12)
	at processPromiseRejections (internal/process/promises.js:245:33)
	at processTicksAndRejections (internal/process/task_queues.js:94:32)]
```

**Comment by qarlosalberto** [comment]
Fixed
