### ISSUE TITLE
'go to definition' need click twice to effect if variable is already highlighted

### ISSUE THREAD

**Issue by summerkaka** [TerosTechnology/vscode-terosHDL#205]
**Describe the bug**
running VSCode in MacOS. if I already click on a variable to make it highlighted, the first time I press F12 or right-click 'go to definition' or CMD+click won't jump to definition, but do the action again will. 

if the variable is not selected/highlighted, 'go to definition can work normally.

 - OS: MacOS Catalina
 - VSCode version version 1.60.0

**Comment by qarlosalberto** [comment]
Does it work?

**Comment by summerkaka** [comment]
my description is not correct, it doesn't work.

**Comment by qarlosalberto** [comment]
Then I re-open the issue.

**Comment by qarlosalberto** [comment]
It has been fixed the bug?
