### ISSUE TITLE
Pipe schematic viewer output to vscode console

### ISSUE THREAD

**Issue by saw235** [TerosTechnology/vscode-terosHDL#213]
There is currently no way to debug or understand what the schematic viewer is doing, and why it is stuck loading.
Piping the output to the vscode console debug will go a long time to help understand what is happening. 

In general, each of the features in TerosHDL should be able to pipe their error messages to the vscode console.

![image](https://user-images.githubusercontent.com/10379864/133908707-71d8deb7-cce5-431d-bf86-4b6a75743aa8.png)

**Comment by qarlosalberto** [comment]
Please, install the beta version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

You can download the documentation from: https://drive.google.com/file/d/1KmnixIHoCQvewbJHWp2dauc0Qlr8o99Q/view?usp=sharing

**Comment by saw235** [comment]
Thanks.
