### ISSUE TITLE
Disable Output log

### ISSUE THREAD

**Issue by RafKarr** [TerosTechnology/vscode-terosHDL#228]
First of all, love the update.

I would like to disable the output log popping every time I do a simple Ctrl+I formatting. It is a bit annoying. And I can't find any options in settings or in the documentation about it.  

Thanks !

**Comment by qarlosalberto** [comment]
Could you install and test this beta version? https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest
I have added a check box in the configuration menu -> General

**Comment by RafKarr** [comment]
Fixed, thank you very much !
