### ISSUE TITLE
Open VSX / VSCodium

### ISSUE THREAD

**Issue by patrickrst** [TerosTechnology/vscode-terosHDL#230]
Hello,

Will the new release of the extension, version 2.0.0, also be uploaded to [Open VSX](https://open-vsx.org/extension/teros-technology/teroshdl)?

**Comment by qarlosalberto** [comment]
Sure, next week.

**Comment by patrickrst** [comment]
Thanks! Just checking so it was not forgotten

**Comment by qarlosalberto** [comment]
Done!
