### ISSUE TITLE
Formatting automatically opens the console

### ISSUE THREAD

**Issue by n30phyte** [TerosTechnology/vscode-terosHDL#232]
Hi,
Every time the formatter is used, the console opens up and I lose focus from the document. This makes the feature unusable with Save on Format, since I save a lot by habit. Is it possible to keep the console hidden and not steal control from the editor?

**Comment by qarlosalberto** [comment]
I have released in the market a new version with hot fixes, you can disable the output console: https://terostechnology.github.io/terosHDLdoc/output_console/configuration.html
