### ISSUE TITLE
Go to TerosHDL documentation opens a terminal instead of the documentation in browser

### ISSUE THREAD

**Issue by am9417** [TerosTechnology/vscode-terosHDL#254]
**Describe the bug**
Navigating to "Go to TerosHDL documentation" opens plain terminal window instead of documentation in the browser.

**To Reproduce**
In Visual Studio code, open the command pallette (F1 / Ctrl+Shift+P), and select "Go to TerosHDL Documentation" in the command pallette. Alternatively open the TerosHDL in the side bar and press the small help icon in the Project manager (screenshot 1).

Result (screenshot 2): A new terminal window is opened instead of a browser window.
* Title of the terminal window is the same as the path to the documentation index.html (the HTML file is found in the file system in that path)
* Looks like the "start" prefix has dropped out from the beginning when the command to open the file is executed
* Maybe problems in detecting the environment?

**Environment**
 - OS:
    - Windows 10 Enterprise
    - 21H1
    - 10.‎3.‎2021
    - Build 19043.1237
    - Windows Feature Experience Pack 120.2212.3530.0

 - VSCode: 
   - Version: 1.61.0 (system setup)
   - Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
   - Date: 2021-10-07T18:13:09.652Z
   - Electron: 13.5.1
   - Chrome: 91.0.4472.164
   - Node.js: 14.16.0
   - V8: 9.1.269.39-electron.0
   - OS: Windows_NT x64 10.0.19043

**Screenshots**
***Screenshot 1***
![image](https://user-images.githubusercontent.com/10899115/137120378-5dbfee80-c0a6-450a-9ec9-da24ce60f67e.png)

***Screenshot 2***
![image](https://user-images.githubusercontent.com/10899115/137120658-0c42a6bb-5991-47e4-91c5-614d0b740d18.png)

**Comment by qarlosalberto** [comment]
Check the beta version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

**Comment by am9417** [comment]
Sorry, I hadn't time to test with the beta version.

Yes, it does work now on 2.0.3!
