### ISSUE TITLE
Bug on fixing RTL indentation by VSG

### ISSUE THREAD

**Issue by oksyassine** [TerosTechnology/vscode-terosHDL#262]
**Describe the bug**

**To Reproduce**
When configuring the indent size to 4 by this, this is the config file:
rule:
  global:
    indentSize:4

the indentation violation has been raised but when I try to fix it it indent by only 2 not 4.

**Code**
Any code

**Please complete the following information:**
 - OS: Linux
 - VSCode version version 1.61

**Comment by qarlosalberto** [comment]
fixed on v5.0.0
