### ISSUE TITLE
Add .fst and .gtkw file binding to GTKWave

### ISSUE THREAD

**Issue by suzizecat** [TerosTechnology/vscode-terosHDL#276]
Hey, would it be possible to add support for .fst (waveforms) and .gtkw (GTKWave configuration) to be automatically opened by GTKWave ?

The command is simply `gtkwave[.exe] <file>` for both of those (same as .ghw or .vcd) .

Best regards !

**Comment by qarlosalberto** [comment]
Yes, also I will add a field for the installation path
