### ISSUE TITLE
Not recognized state change when doing it inside a for loop 

### ISSUE THREAD

**Issue by mfernandezt03** [TerosTechnology/vscode-terosHDL#285]
**Describe the bug**
I'm creating a state machine that has to deal with four channels of input data. The machine changes it state according to the state of each chanel. Now, when I see the diagram, I don't find the changes between states that are instantiated inside the for loop created. 

**To Reproduce**
Create a state machine that handles different channels or inputs and changes it state according to that. 

**Code**
```
always@(posedge clk)begin
    case(state)
          caseA: state <= caseB;
          caseB: state <= case C;
          caseC: begin
                if(rx_data[0] == 8'hFF)begin
                      state <= caseD;
                      for( int k=1; k<4; k=k+1)begin
                           case(data[k])
                                   case1:  do_sth;
                                   case2:  do_sth;
                                   default: begin
                                          state <= caseZ;   // this is what does not appear in the diagram
                                   end
                           endcase
                      end
                end
          end
          more_cases:
          caseZ: state <= caseA;
    endcase
end
```

**Please complete the following information:**
 - OS: Ubuntu 20.04.3 LTS
 - VSCode version 1.63.2

**Screenshots**

![code](https://user-images.githubusercontent.com/82542383/147715813-c6b4fa1f-4dd3-416c-8cd0-6760216b906a.png)

![stm_ADC_pipeline_00](https://user-images.githubusercontent.com/82542383/147715896-980b37bb-55f3-43d9-b953-6bf488ff940b.png)

**Comment by qarlosalberto** [comment]
Could you provide a simple code to reproduce the problem? So I can debug it

**Comment by qarlosalberto** [comment]
I see the problem. Currently the loops in the state machine aren't supported.

**Comment by mfernandezt03** [comment]
Thanks!
