### ISSUE TITLE
Add support for yowasp-yosys in TerosHDL with a virtualenv under Windows 10 (and Anaconda 3)

### ISSUE THREAD

**Issue by LispEngineer** [TerosTechnology/vscode-terosHDL#304]
**Describe the bug**
Inability to invoke `yowasp-yosys` in an Anaconda VirtualEnv in Windows 10.

**To Reproduce**
Just click "show the netlist" on a TerosHDL project in VS Code.

```
yowasp-yosys -p "read_verilog -sv ...files...; proc; opt; write_json teroshdl_yosys_output.json; stat"
'yowasp-yosys' is not recognized as an internal or external command,
operable program or batch file.
2022-02-25 17:24:55: Configure (https://terostechnology.github.io/terosHDLdoc/netlist/configuration.html) Yosys or install YoWASP: pip install yowasp-yosys
```

I could probably install this in a system-wide directory on the Path, but frankly I do everything in virtual environments in Python.

**Code**
OS: Windows 10
VSCode: 1.64.2 (user setup)

Thank you!

**Comment by qarlosalberto** [comment]
fixed
