### ISSUE TITLE
Diagram : Special symbol for clk and inverted signals

### ISSUE THREAD

**Issue by SebastianHambura** [TerosTechnology/vscode-terosHDL#315]
I've read here (https://www.reddit.com/r/FPGA/comments/gukpjj/does_anyone_know_of_an_opensource_and_lightweight/) that terosHDL uses Symbolator for diagrams. If that is the case, would it be possible to update the version used ? 
It would be nice to have a the triangle for the clk signal, and the circle for the active low signals (as well as the other customization options available).

**Comment by qarlosalberto** [comment]
No, we use our own diagram generator. But feel free to open other issues with your customization options requests.
