### ISSUE TITLE
Can't find definitions for localparam, but it can for parameter

### ISSUE THREAD

**Issue by MasterJubei** [TerosTechnology/vscode-terosHDL#324]
Hello, great project

One small bug I found is that it cannot find the definitions of localparam variables

![image](https://user-images.githubusercontent.com/8354691/176253174-4e3b3fff-6c81-4224-842f-6f78b4d0099c.png)

But if I set it to parameter, it will work

![image](https://user-images.githubusercontent.com/8354691/176253304-2bde285b-18eb-49fb-b2c2-f48227f67b11.png)

**Comment by qarlosalberto** [comment]
could you provide a code example?

**Comment by MasterJubei** [comment]
> 

Hey not sure, but it looks like it has been fixed(or I can't reproduce it). Both localparam and parameter both show the definition now.

`module localparam_test();

    localparam NUM_BITS = 3;
    // parameter NUM_BITS = 3;
    
    integer i = 0;
    initial begin
        for(i = 0; i < NUM_BITS; i = i+ 1) begin
            $display("i = %d", i);
        end
    end
endmodule`
