### ISSUE TITLE
Two-dimensional array port export to diagram is abnormal

### ISSUE THREAD

**Issue by zengzhengqi0524** [TerosTechnology/vscode-terosHDL#330]
The diagram only shows  one vector.

**Comment by qarlosalberto** [comment]
Please, share an reproducible example.

**Comment by zengzhengqi0524** [comment]
> Please, share an reproducible example.

![8adc121a-4c90-4c37-98f0-d98cdcc6811d.png](https://user-images.githubusercontent.com/50767486/180167913-9799c8d3-64dd-49e6-8d5c-5c8c80d383c9.png)

**Comment by qarlosalberto** [comment]
Please, share an example in **code**, not as image.

**Comment by qarlosalberto** [comment]
In code, not image.
