### ISSUE TITLE
'show netlist' cannot find the top module

### ISSUE THREAD

**Issue by GrootLiu** [TerosTechnology/vscode-terosHDL#331]
when i use the show netlist button to use yosys, I found the plugin always show the sub module

So I modified the source code of the plugin in the file :` teros-technology.teroshdl-2.0.7/out/lib/netlist_viewer/netlist_viewer.js`
to identify the top moule

- before

```var script_code;
const script_code = `${cmd_files}; hierarchy -top top; proc; opt; write_json ${output_path_filename}; stat`;
```

- after

```var script_code;
if (cmd_files === "read_verilog -sv top.v")
{
    script_code = `${cmd_files}; hierarchy -top top; proc; opt; write_json ${output_path_filename}; stat`;
}
else
{
    script_code = `${cmd_files}; proc; opt; write_json ${output_path_filename}; stat`;
}
```
but to use this function, we must name the top module by top.

![1658404064268](https://user-images.githubusercontent.com/55238899/180206595-e3831101-d914-4678-893d-9f99d1c9fd5e.jpg)

**Comment by qarlosalberto** [comment]
Could you share a reproducible example? (In code)

**Comment by GrootOfSDUST** [comment]
This is my structure
![image](https://user-images.githubusercontent.com/55238899/180232301-d54f1155-aa99-48a3-bdc7-488cc1832686.png)
the plugin will always set the id.v as top module before i modify the code

**Comment by qarlosalberto** [comment]
Have 1 file or more?
What button are you using?
Are you using the project manager?

**Comment by GrootOfSDUST** [comment]
the button i used is 'nestlist viewer'
![image](https://user-images.githubusercontent.com/55238899/180234430-9bdd0ed4-7dac-479f-9c25-05e2c3cf0cd3.png)

and i used the project manager
![image](https://user-images.githubusercontent.com/55238899/180234361-f591fc78-32b7-4b10-8200-488050d53f95.png)

**Comment by qarlosalberto** [comment]
In the project manager, rigth? There are 2 buttons:

https://terostechnology.github.io/terosHDLdoc/netlist/start.html

https://terostechnology.github.io/terosHDLdoc/project_manager/hierarchy.html

**Comment by GrootOfSDUST** [comment]
the plugin's yosys dosen't have the capability to find the top module, so I edited the source code as I showed before.

**Comment by GrootOfSDUST** [comment]
> In the project manager, rigth? There are 2 buttons:
> 
> https://terostechnology.github.io/terosHDLdoc/netlist/start.html
> 
> https://terostechnology.github.io/terosHDLdoc/project_manager/hierarchy.html

i used the first one, because the second will show nothing to me.
![image](https://user-images.githubusercontent.com/55238899/180238640-163e0868-a059-44b9-81f4-ff1bf817d4ee.png)

and, if i click the first 'netlist viewer', the schemetic viewer won't show netlist before I switch the schmetic viewer to anthor and switch back
I will show you tomorrow after I make this bug to a GIF

**Comment by qarlosalberto** [comment]
Please, share a complete example in **code**, not an image. So I can reproduce it.

**Comment by qarlosalberto** [comment]
Okk. I could take a look the next week. It would be really useful if you
can share all your project. Or a minimum example. In other case it's
difficult for me reproduce your error.

**Comment by qarlosalberto** [comment]
fixed
