### ISSUE TITLE
Schematic viewer "Save as SVG" not working.

### ISSUE THREAD

**Issue by RichardRo** [TerosTechnology/vscode-terosHDL#348]
Tried to "Save as SVG" in schematic viewer, but nothing was generated. 
"Save as SVG" in module documentation works.
Compared the 2 copies of code, seems the generated path has a "/" prefix. On Windows, the full path will be something like "/C:/x.svg".
This has been fixed in documeter.ts by normalize_path(), but not in netlist_viewer.ts.
Will you please help to fix this? Thanks.

**Comment by qarlosalberto** [comment]
Check if it works in this beta version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest
