### ISSUE TITLE
TerosHDL configuration not working

### ISSUE THREAD

**Issue by AviadMal** [TerosTechnology/vscode-terosHDL#350]
**Describe the bug**
From version 2.0.7 and higher, teroshdl configuration is not displayed well in Linux, and does not allow saving the configuration set by the user.

**To Reproduce**
Upload the terosHDL configuration in Linux.

**Please complete the following information:**
 - OS: linux
 - VSCode version version: 2.0.7/2.0.8(last)

**Comment by qarlosalberto** [comment]
Could you share a screenshot?

**Comment by AviadMal** [comment]
![Capture](https://user-images.githubusercontent.com/117912294/201124602-afc6b2cc-24a7-40e4-bf9c-06b59c2eaa56.JPG)

**Comment by qarlosalberto** [comment]
Could you take a screenshot in the full screen? I would like to know what is the webview position.
