### ISSUE TITLE
[QUESTION / FEATURE REQUEST]: Export TerosHDL settings?

### ISSUE THREAD

**Issue by sibeov** [TerosTechnology/vscode-terosHDL#366]
# Export TerosHDL Settings
## Intro
Refering to the main topic of the issue. Is is possible? Loved it when all the settings where in the VScodes `settings.json` file.
As far as I have experienced TerosHDL now it does not seem that the settings are synced between computers when using VScode's sync feature. Correct?

## Bug
N.A.

## How to reproduce
N.A.

**Comment by qarlosalberto** [comment]
This feature it included in the new major version. You can test the beta version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/3.4.0

**Comment by qarlosalberto** [comment]
fixed on v5.0.0
