### ISSUE TITLE
module 'edalize' has no attribute 'get_edatool'

### ISSUE THREAD

**Issue by petrcechura** [TerosTechnology/vscode-terosHDL#388]
I am not able to run any simulation due to error that says "module 'edalize' has no attribute 'get_edatool' ". I tried to reinstall everything, use old versions of TerosHDL, but nothing helps. On Windows it works without any issue (I have dualboot). 

Code is simple, it doesn't matter what I try to run.
```
library ieee;
    use ieee.std_logic_1164.all;

entity aaa is
    port (
        a, b   : in std_logic;
        c : out std_logic
    );
end entity;

architecture rtl of aaa is

begin
    c <= a and b;
   
end architecture;
``` 

 - OS: [e.g.Ubuntu 18.04]
 - VSCode version version [e.g. 22]

**Screenshots**
![image](https://user-images.githubusercontent.com/103133298/228973277-1fdba06c-8d22-497b-b419-38c3e287adfc.png)

**Comment by qarlosalberto** [comment]
I have fixed it in the latest version. Feel free to re-open the issue if it doesn't work.
