### ISSUE TITLE
Trouble activating virtual environment on Windows

### ISSUE THREAD

**Issue by tj-scherer** [TerosTechnology/vscode-terosHDL#397]
Hello! I am experiencing an issue with using my virtual environment on Windows. I have created it directly through vscode in my workspace, and it is named `.venv`. Following the guide [here](https://terostechnology.github.io/terosHDLdoc/configuration/python.html#example-with-virtualenv) indicates that the python path is showing my python path to be the main installation, not the activated virtual environment. It also shows that the deps are not installed, which they are (on the venv). Is this still the correct thing to put in the path config?

`. .venv/bin/activate & python`

 - OS: Windows 10
 - VSCode version version 1.77.3

![image](https://user-images.githubusercontent.com/68401889/235531669-5a3aa344-7d06-4490-8dc1-9922e4c220d6.png)
![image](https://user-images.githubusercontent.com/68401889/235531766-399c406e-3f92-4ed6-8c44-2dbeca746f79.png)
![image](https://user-images.githubusercontent.com/68401889/235531819-23547fc2-d7f8-499b-8572-d6bac90e00cc.png)

EDIT: also tried and failed with the following:
```
call .venv\Scripts\activate & python
call .venv\Scripts\activate.bat & python
. .venv\Scripts\activate & python
. .venv/Scripts/activate & python
. & call .venv\Scripts\activate & python
```

EDIT: some of the commands I tried work in the command prompt
![image](https://user-images.githubusercontent.com/68401889/235532616-d1c6a4b9-fbd6-4042-a67e-784dba4c8b62.png)

**Comment by tafkos** [comment]
@tj-scherer Try to activate environment in command line first (cmd.exe), then run `code` from command line with activated environment. Works for `conda`.

![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/30288817/e82809da-cbee-4f46-b725-9a2389479dcb)

**Comment by timothyscherer** [comment]
I was able to make this work by creating a "global" virtual environment specifically for Teros.

```
cd C:/work/teroshdl
python -m venv .venv
.venv/Scripts/activate
pip install teroshdl
```

Then, my Teros configuration contains `C:/work/teroshdl/.venv/Scripts/python.exe` in the python3 binary path, no environment activation required.

I had the misconception that I should be pip installing teros in every workspace, but this approach makes much more sense overall. The new documentation definitely helped clear this up.
