### ISSUE TITLE
Packages not found in v0.0.1

### ISSUE THREAD

**Issue by lukipedio** [TerosTechnology/vscode-terosHDL#4]
When I open a source file with use clause, I got the following error notification

![image](https://user-images.githubusercontent.com/16959881/85370161-95870b80-b52e-11ea-8836-d066a10c5bb7.png)

**Comment by qarlosalberto** [comment]
It's normal. You are using the GHDL linter.  The command -s (http://ghdl.free.fr/ghdl/Check-syntax-command.html) does both syntax and semantic checking. You can change the linter or disable it.

**Comment by lukipedio** [comment]
Ok. I see.
I have menaged to change linter by manually editing the <userdir>\.vscode\extensions\teros-technology.teroshdl-0.0.1\package.json in Win10.
Is there a better way to do it?
I have changed from ghdl (Ihave not installed) to modelsim. Now I don't get the error anymore.

**Comment by lukipedio** [comment]
Ok. At first I was not able to find the extension in the Extensions search. I missed to search in the @installed group.
So now I can modify the extension settings through the GUI instead of modifying the json file.
