### ISSUE TITLE
Difference between v2 and v5

### ISSUE THREAD

**Issue by wimille** [TerosTechnology/vscode-terosHDL#415]
Hi,

maybe i don't see the associated post or message, but what is the difference between version v2.0.13 available on the vscode market and version 5.0.1 available throught the github repository ?

Sorry if the question has been already asked ?

Regards

**Comment by qarlosalberto** [comment]
- I have fixed a lot of bugs.
- Support for Raptor in RapidSilicon.
- Watchers for VUnit and CSV.
- New tool manager.
- New configuration page.

https://terostechnology.github.io/teroshdl-docusaurus-doc/

**Comment by wimille** [comment]
Ok thank you for your answer. 
Why this version is not available through vscode marketplace ?

**Comment by qarlosalberto** [comment]
Because it's a beta version.

**Comment by wimille** [comment]
Thank you for all this precisions. 
I really enjoy your work.
