### ISSUE TITLE
If path has white space, linter won't work

### ISSUE THREAD

**Issue by Devil-SX** [TerosTechnology/vscode-terosHDL#420]
**Describe the bug**
We can see that teroshdl used both double quotes and escape characters, resulting in the inability to handle spaces correctly.

**Please complete the following information:**
 - Ubuntu22.04
 - VSCode version 1.79.2

**Screenshots**
![2023-07-16_09-15](https://github.com/TerosTechnology/vscode-terosHDL/assets/77198466/ac93762a-4b44-442e-a5bc-f3bfa70ac213)

**Comment by qarlosalberto** [comment]
Check if the latest version in the market (5.0.5) fixes it.

**Comment by elpollodiablo84** [comment]
If I'm not mistaken, it seems there is the same problem in the dependency graph generator, since I'm getting an error stating that "C:\Program" is not a known command (vscode is installed in "C:\Program Files\....").

**Comment by qarlosalberto** [comment]
Could you show a screenshot with the error?

**Comment by elpollodiablo84** [comment]
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/37348156/8702055d-bbad-4589-97f3-1b293ea0a3e4)
The error is in italian maybe because is a system error?

**Comment by qarlosalberto** [comment]
Try this version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

Not sure if your problem is related to the VSCode installation path or due to the Python path. Has your Python path white spaces?

**Comment by elpollodiablo84** [comment]
Both my python path and vscode path have spaces. I tried your suggested version but the error is still there...
I can generate documentation without any issues, and I can format/lint with VSG correctly.

**Comment by qarlosalberto** [comment]
Try with this version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

**Comment by elpollodiablo84** [comment]
> Try with this version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

I still got the error...

> Try to escape you Python path and let me know if it works.

How should escape it? I'm using the system path, so I'm not declaring it in the configuration menu.
If the problem is the python path, why VSG is still working?
Is there a way to log more data (by my side) during Teros execution to understand what call fails?

**Comment by qarlosalberto** [comment]
Yes I will add more logs.

VSG doesn't fail because it's a "binary" installed in the system path. 

Meanwhile, with is the output of..?

https://terostechnology.github.io/terosHDLdoc/docs/getting_started/installation#validating-installation

**Comment by elpollodiablo84** [comment]
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/37348156/8a6194f7-2eb8-4508-823b-be7d80c587e0)
It seems it's all fine

**Comment by qarlosalberto** [comment]
I think that the problem is related to the white space in the Python path. This version should fix it: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

**Comment by elpollodiablo84** [comment]
> I think that the problem is related to the white space in the Python path. This version should fix it: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest

It works! 🎉🎉🎉
Well done, thank you!

**Comment by qarlosalberto** [comment]
Please, use the latest version 5.0.7. Feel free to re-open the issue if the problem continues.
