### ISSUE TITLE
'""' not recognized as an internal or external command

### ISSUE THREAD

**Issue by pintert3** [TerosTechnology/vscode-terosHDL#432]
I keep getting the error: `'""' not recognized as an internal or external command` when I try to run, ever since I updated to v5. When I click `Check dependencies` it says:

```
2023-07-26 08:01:11.688 [error] ---> Python not found
2023-07-26 08:01:12.073 [info] --->  Make found
```

 - OS: Windows 11
 - VSCode version version 1.80.1

**Comment by qarlosalberto** [comment]
What is your python3 configuration path?

**Comment by qarlosalberto** [comment]
And when you have the error?

**Comment by pintert3** [comment]
I'm using the Windows default path. And the error happened yesterday, almost immediately after updating terosHDL

**Comment by qarlosalberto** [comment]
Could you share a screenshot of the error?

**Comment by pintert3** [comment]
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/26062452/84793410-8ca6-4469-adda-e5d5aec47cf0)

There you go!

**Comment by pintert3** [comment]
It appears it's cause it couldn't figure out the python installation. I now have to manually insert it in the configuration menu in `General` for it to work. It now works when I input `C:/Users/Asus/AppData/Local/Programs/Python/Python311/python.exe` as the install path.

**Comment by dsioffe** [comment]
I have a similar error. Here is the output after running vscode:

2023-07-27 17:25:54.364 [error] Error while getting dependency graph.
2023-07-27 17:25:54.364 [error] Traceback (most recent call last):
  File "c:\Users\<myname>\.vscode\extensions\teros-technology.teroshdl-5.0.6\node_modules\teroshdl2\out\project_manager\dependency\vunit_dependency.py", line 28, in <module>
    import vanity.project as pj
ModuleNotFoundError: No module named 'vunit'

This is how dependency checking looks like

2023-07-27 17:30:51.820 [info] Checking dependencies...
2023-07-27 17:30:51.920 [info] --->  Python found: "C:\Users\<myname>\AppData\Local\Programs\Python\Python311\python.exe"
2023-07-27 17:30:51.962 [error] --->  vunit not found
2023-07-27 17:30:52.002 [error] --->  cocotb not found
2023-07-27 17:30:52.043 [error] --->  edalize not found
2023-07-27 17:30:52.068 [info] --->  Make found

This means that Python is installed normally

**Comment by qarlosalberto** [comment]
@dsioffe you need to install Vunit: https://terostechnology.github.io/terosHDLdoc/docs/getting_started/installation#python3-package-dependencies

**Comment by dsioffe** [comment]
Thanks!I did it.Now there is one error left:cocotb not foundHow to fix it? 27.07.2023, 21:02, "Carlos Alberto Ruiz Naranjo" ***@***.***>***@***.*** you need to install Vunit: https://terostechnology.github.io/terosHDLdoc/docs/getting_started/installation#python3-package-dependencies—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>  -- С уважениемДмитрий ***@***.***://vk.com/dsioffe

**Comment by qarlosalberto** [comment]
Cocotb it's an optional dependency

**Comment by qarlosalberto** [comment]
I have added more log in 5.0.7

**Comment by pintert3** [comment]
Meanwhile, does this mean no more auto detecting the default python installation on windows? Cause the documentation says it should be able to.

**Comment by qarlosalberto** [comment]
It does it. But I don't know what is happening in your system.
