### ISSUE TITLE
Deprecation warning while updating teroshdl python package

### ISSUE THREAD

**Issue by elpollodiablo84** [TerosTechnology/vscode-terosHDL#459]
While updating python packages with `pip`, the following warning appears:

> DEPRECATION: teroshdl 2.1.2 has a non-standard dependency specifier yowasp-yosys>=0.8.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of teroshdl or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by qarlosalberto** [comment]
Fixed.
