### ISSUE TITLE
UX/GUI issue

### ISSUE THREAD

**Issue by the-moog** [TerosTechnology/vscode-terosHDL#469]
**Describe the bug**
The scroll bar on the TerosHDL panel can't scroll in a way such as to reveal the lower two of the five huge blue button without first collapsing all of the panel subsections above it.  There is no collapse all button.   The default is to expand all sections.
Note (in the attached picture), the scroll bar thinks it can go further as there is a gap below it, but there is no way to make it do that.

**To Reproduce**
100% reproducable
I have no idea why it does this - screen res, graphics settings - scaling perhaps, driver, OS version?

**Code**
n/a

**Please complete the following information:**
 - OS: WSL/Remote on Ubuntu 23.04 hosted in Win 10 Enterprise, VSCode runs in Windows.
 - VSCode: 1.82.2

**Screenshots**
<img width="217" alt="tarrosbug" src="https://github.com/TerosTechnology/vscode-terosHDL/assets/3725802/41eb982d-79c6-4878-ac09-50f716bf2af4">

**Comment by qarlosalberto** [comment]
This is a VSCode issue. Not related to TerosHDL.
Check the grey scroll bar:

![imagen](https://github.com/user-attachments/assets/02575152-5e50-497b-aa20-6ee9a326110d)
