### ISSUE TITLE
Generate template error in v0.0.1

### ISSUE THREAD

**Issue by lukipedio** [TerosTechnology/vscode-terosHDL#5]
If I click on the "Generate template" icon, I get the followeing error in the "Develop Tools console:
![image](https://user-images.githubusercontent.com/16959881/85459748-ce60c800-b5a2-11ea-9d20-efc4d330adff.png)

I am working on Windows 10 Version 10.0.19041 build 19041.

**Comment by smgl9** [comment]
In Windows the extension is currently broken. And the error you mention is probably a change in an interface. We'll check it out but the extension is likely to be unstable until the official release. Especially in Windows but thanks a lot for the report. We'll let you know as soon as the errors are fixed.

**Comment by lukipedio** [comment]
I will stop testing Windows extension until there will be a notification it is not broken anymore.
I will switch to Linux for further testing.

**Comment by qarlosalberto** [comment]
@AriesKo we have fixed the errors in a new version: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/v0.0.2
