### ISSUE TITLE
Module documentation : comment spread over several lines

### ISSUE THREAD

**Issue by rsek1498** [TerosTechnology/vscode-terosHDL#506]
When a comment is spread over several lines, only the first line appears with module documentation.

Example:
signal c2p_i : t_c2p;  --! Internal version of output
                               --! comment on second line
signal igr   : std_logic; --! comment igr

Result in attached file

![screenshot](https://github.com/TerosTechnology/vscode-terosHDL/assets/142711770/57b6f76b-b81e-436a-9af7-b825b4d50ec3)

**Comment by qarlosalberto** [comment]
This is expected. If you want to use multiline you have to put the commets over the port:

```
--! Internal version of output
--! comment on second line
signal c2p_i : t_c2p;
signal igr : std_logic; --! comment igr
```

![imagen](https://github.com/user-attachments/assets/01d3dc18-1a3a-4d86-a045-beaf4cae340e)
