### ISSUE TITLE
Version 6.0.0 shows that the project instantiation structure hierarchy function is invalid.

### ISSUE THREAD

**Issue by xpww** [TerosTechnology/vscode-terosHDL#534]
**Describe the bug**
Version 6.0.0 shows that the project instantiation structure hierarchy function is invalid，Currently, only one instantiated module is displayed, and the many instantiated modules inside it cannot be detected.

**To Reproduce**

**Code**
Code to reproduce the error.

**Please complete the following information:**
 - OS: [e.g.Ubuntu 18.04]
 - VSCode version version [e.g. 22]

**Screenshots**
v6.0.0:
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/88141892/f604963e-6d35-4982-a84d-a1acf00e4528)
v5.0.12:
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/88141892/f84664d8-6348-4973-adba-f39b833fb3ac)

**Additional context**

**Comment by qarlosalberto** [comment]
fixed: https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/v6.0.0alpha
