### ISSUE TITLE
GHDL Sample Project does not find library "mylib"

### ISSUE THREAD

**Issue by Detzi88** [TerosTechnology/vscode-terosHDL#585]
**Describe the bug**
When i install TerosHDL in VScode and open the sample project for GHDL it cant find the library "mylib".

**To Reproduce**
open the sample project for ghdl. Check errors.

**Code**
as provided with the sample project

**System Information**
VScode:
    Version: 1.86.2
    Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
    Date: 2024-02-13T19:41:37.860Z
    Electron: 27.2.3
    ElectronBuildId: 26908389
    Chromium: 118.0.5993.159
    Node.js: 18.17.1
    V8: 11.8.172.18-electron.0

TerosHDL: Version 5.0.12
OS: Ubuntu 22.04 LTS
Kernel: Linux x64 6.1.0-1034-oem

**Comment by qarlosalberto** [comment]
Select `VHDL_LS` instead `GHDL`. Currently TerosHDL doesn't support multi lib for `GHDL` linter.

![imagen](https://github.com/user-attachments/assets/22cb1dbd-bcae-4f7a-9fda-6207a1e78746)
