### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AzhakAnwar** [TerosTechnology/vscode-terosHDL#59]
- Issue Type: `Performance`
- Extension Name: `teroshdl`
- Extension Version: `0.0.8`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\azhak\AppData\Local\Temp\teros-technology.teroshdl-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smgl9** [comment]
Thank you for your feedback @AzhakAnwar !
We are aware about some performance issues and we are making some improvements. 
The problems are noticeable when it comes to parse large files. Is it your problem when you work with large files or is there any other problem?
