### ISSUE TITLE
Documentation: type record

### ISSUE THREAD

**Issue by qarlosalberto** [TerosTechnology/vscode-terosHDL#600]
Could you update the documentation? You only need to modify this doc: https://github.com/TerosTechnology/terosHDLdoc/blob/main/docs/08-documenter/03-vhdl_elements.mdx

@gmartina

**Comment by gmartina** [comment]
> Could you update the documentation? You only need to modify this doc: https://github.com/TerosTechnology/terosHDLdoc/blob/main/docs/08-documenter/03-vhdl_elements.mdx
> 
> @gmartina

https://github.com/TerosTechnology/terosHDLdoc/pull/25

**Comment by qarlosalberto** [comment]
thanks for that!
