### ISSUE TITLE
Error finding raptor

### ISSUE THREAD

**Issue by MarkoMk** [TerosTechnology/vscode-terosHDL#612]
I am trying to run a project and even though I se everyghing up like in the tutorials on the webpage I am getting the following error:
/Raptor/build/bin/raptor: not found

Is it possible that TerosHDL only works with raptor version 2023.04 and I curently have version 2024.05?

**Comment by qarlosalberto** [comment]
Can you share the complete log?

**Comment by MarkoMk** [comment]
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/46170875/3a8d68fa-135c-4052-b3f3-9cc9ba0cb66d)

**Comment by qarlosalberto** [comment]
Are you sure that the binary is there? Are the permissions correct? Is it an executable?

**Comment by MarkoMk** [comment]
If we are talking about the raptor shell script, it is there and it has all the correct permissios. It' also executable.

**Comment by qarlosalberto** [comment]
Can you type "/Raptor/build/share/raptor --version" in the terminal and to share a screenshot?

**Comment by MarkoMk** [comment]
It's the same whether it is in share or bin folder, same version, doesn't work on both...
![image](https://github.com/TerosTechnology/vscode-terosHDL/assets/46170875/c7732ead-544c-4969-8425-48e974b0c082)

**Comment by qarlosalberto** [comment]
Please double check your configuration in TerosHDL. I think that the binary path it's not correct. And check that your are using the complete path

**Comment by MarkoMk** [comment]
I think writing the bin path like this: ~/Raptor/build/bin fixed the issue with being unable to find the raptor shell script. Not getting that error anymore.

**Comment by qarlosalberto** [comment]
Great! I close the issue.
