### ISSUE TITLE
Unable to select NVC as simulator

### ISSUE THREAD

**Issue by gfcwfzkm** [TerosTechnology/vscode-terosHDL#651]
**Describe the bug**
While TerosHDL suggests NVC-support by having it listed in the Settings Menu under `Tools`, it cannot be selected in `Tools: General`.

**To Reproduce**
Open the Settings Menu and look in `Tools -> General` for an NVC option in the `Select a tool, framework, simulator...` drop-down menu.

**Please complete the following information:**
 - OS: Windows 11 Pro
 - VSCode version version 1.92.2
 - TerosHDL: 6.0.3

**Comment by qarlosalberto** [comment]
I will remove it. Currently there isn't support for NVC.
