### ISSUE TITLE
Analysis doesn't seem to work with WSL Remote in VS Code

### ISSUE THREAD

**Issue by hughesjs** [TerosTechnology/vscode-terosHDL#81]
I'm using WSL remote and my Makefile uses these flags:

`GHDLFLAGS=--std=08  --workdir=./$(TMPDIR) --warn-no-hide`

where `TMPDIR=build`.

I've then got TerosHDL set with these GHDL settings:

![image](https://user-images.githubusercontent.com/4203766/109884300-a1f26500-7c74-11eb-9068-7f1dfb2138bb.png)

But I get unit "x" not found in library "work" almost everywhere despite the fact that running my makefile works just fine so there's no GHDL errors.

Any ideas?

**Comment by hughesjs** [comment]
This might not actually be an issue with WSL as I'm now having the same issue on an arch installation.

The linter doesn't seem to be detecting work.x includes...

![image](https://user-images.githubusercontent.com/4203766/114319538-d5dd6780-9b09-11eb-95e2-988019f9241e.png)

This is even after setting up a work library in the project manager:

![image](https://user-images.githubusercontent.com/4203766/114319600-08876000-9b0a-11eb-8487-3fe6cfba1ffc.png)

My linter settings look fine to me:

![image](https://user-images.githubusercontent.com/4203766/114319621-1e952080-9b0a-11eb-960c-804e379005f0.png)

Am I missing something?

**Comment by qarlosalberto** [comment]
It works fine, GHDL only lints the current file.
You can try the lastest beta version with RustHDL:
https://github.com/TerosTechnology/vscode-terosHDL/releases/tag/latest
Disable the linter (none) or the errors will be duplicated.

**Comment by hughesjs** [comment]
Ahh okay... that seems like something that would be useful to have

Does RustHDL lint the entire project?

**Comment by qarlosalberto** [comment]
Yes!

**Comment by hughesjs** [comment]
Dude, that's so much better! I love it! Great job!

Thanks so much!
