### ISSUE TITLE
Extension host issues

### ISSUE THREAD

**Issue by ZirconfleX** [TerosTechnology/vscode-terosHDL#87]
Hi,

On regularly base I get a popup about an extension host being unresponsive
![Screenshot from 2021-03-24 11-32-03](https://user-images.githubusercontent.com/9218998/112296873-84258800-8c95-11eb-9946-8da581fb7ca0.png)

The popup lets you restart the server or go to developer mode.
In developer mode the errors as showed in attached figure pop out.

What can be wrong?

Thanks

**Comment by qarlosalberto** [comment]
Hi! Could you attach an image with the previous output to "Extension host terminated..." ?

**Comment by ZirconfleX** [comment]
Dear Carlos,

This is the popup I get:

I copied all text for the errors in teh developers tools terminal
     Took screenshots because else it's unreadable.

Hope this si what you are looking for,

Regards,

Marc

**Comment by qarlosalberto** [comment]
Check the beta version.

**Comment by ZirconfleX** [comment]
I did, and it seems to work!
Guess this can be closed.

**Comment by qarlosalberto** [comment]
Nice!
