### ISSUE TITLE
Using xvhdl /xsim as linter --> hint about an annoyance

### ISSUE THREAD

**Issue by ZirconfleX** [TerosTechnology/vscode-terosHDL#98]
Hi,

It seems that the extension, when using xvhdl as linter, creates in my home directory (Linux) a xsim directory and xvhdl.pb file.
Make sure these files are created in the project directory making uses of the extension.
Even better; make sure those two things are created in a hidden folder.

Just a hint, not a bug but an annoyance.

Cheers

**Comment by suzizecat** [comment]
Confirmed both the issue and the annoyances.

**Comment by qarlosalberto** [comment]
Fixed in the lastest beta version.

**Comment by pintert3** [comment]
I'm currently getting this. Seems like a regression
